name: Python application

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Ejecutar aplicacion
      run: python app.py
        
    - name: Test with pytest
      run: |
        pytest
    - name: Simulando deploy
      run: echo 'Desplegando app de python...'